workdir: "/path/"
threads: 24
tools_path:
  ganon: "/path/ganon/"
  krakenuniq: ""
  kraken: ""
  centrifuge: ""

databases:
  db_name1: 
    fasta: "/path/sequences.fna"
    nodes: "/path/nodes.dmp"
    merged: "/path/merged.dmp"
    names: "/path/names.dmp"
    acc_len_taxid_assembly: "/path/acc_len_taxid_assembly.txt"
  db_name2: 
    fasta: "/path/sequences.fna"
    nodes: "/path/nodes.dmp"
    merged: "/path/merged.dmp"
    names: "/path/names.dmp"
    acc_len_taxid_assembly: "/path/acc_len_taxid_assembly.txt"
  db_name3: 
    fasta: "/path/sequences.fna"
    nodes: "/path/nodes.dmp"
    merged: "/path/merged.dmp"
    names: "/path/names.dmp"
    acc_len_taxid_assembly: "/path/acc_len_taxid_assembly.txt"

run:
  ganon:
    db_name1:
      config_name1: "-x 1"
      config_name2: "-x 2"
    db_name2:
      config_name1: "-x 1"
  krakenuniq:
    db_name1:
      config_name1: "-x 1"
      config_name2: "-x 2"
    db_name3:
      config_name1: "-x 1"

