workdir: "/path/" 
threads: 24

tools_path:
  ganon: "/path/ganon/"
  krakenuniq: ""
  kraken: ""
  centrifuge: ""
  diamond: ""
  clark: ""
  amber: ""

samples:
  sample_name1:
    fq1: "/path/reads.1.fq.gz"
    fq2: ""
    gt: "/path/seqid_assembly_taxid.tsv"

databases:
  db_name1:
    acc_len_taxid_assembly: "/path/acc_len_taxid_assembly.txt"

run:
  ganon:
    db_name1:
      config_name1:
        prefix: "/path/db1/config1/"
        parameters:
          param_name1: "-a 1"
          param_name2: "-a 2"
      config_name2:
        prefix: "/path/db1/config2/"
        parameters:
          param_name1: "-a 1"
    db_name2:
      config_name1:
        prefix: "/path/db2/config1/"
        parameters:
          param_name1: "-a 1"


